1061 Ability to enable recaptcha
softberg/quantum-php-core pull request #127
Opened 2022-12-30 10:07 UTC by Vahram1995

2022-12-30 11:49 UTC, armanist requested changes
CI is not passed

2022-12-30 11:49 UTC, armanist commented on composer.json
> +        "google/recaptcha": "1.2"
- require.google/recaptcha : exact version constraints (1.2) should be avoided if the package follows semantic versioning

2023-02-09 08:12 UTC, hatik92 approved these changes

2023-03-08 12:22 UTC, armanist approved these changes

2023-03-08 12:32 UTC, merged