Mailer library
softberg/quantum-php-core pull request #134
Opened 2023-04-10 11:39 UTC by armanist

2023-04-10 14:37 UTC, Vahram1995 requested changes

2023-04-10 14:37 UTC, Vahram1995 commented on src/Libraries/Storage/Adapters/Local/LocalFileSystemAdapter.php
> +    public function getLines(string $filename, int $offset = 0, ?int $length = null): array
method can return `false`

2023-04-10 15:26 UTC, andrey-smaelov approved these changes

2023-04-20 07:02 UTC, hatik92 approved these changes

2023-04-20 13:07 UTC, hatik92 commented on src/Libraries/Mailer/Adapters/MandrillAdapter.php
> -                ->setData($data)
for mandrill api_key should be in data
$this->data["key"] = $this->apiKey;

2023-04-20 14:18 UTC, hatik92 commented on src/Libraries/Mailer/Adapters/SendgridAdapter.php
> +            ];
data['content '] should be in array

$this->data['content'] = [
                [
                    'type' => 'text/html',
                    'value' => trim(str_replace("\n", "", $body))
                ]
            ];

2023-04-21 08:24 UTC, hatik92 commented on src/Libraries/Mailer/Adapters/SendgridAdapter.php
> +            'email' => $this->from['email']
add to data from
'name' => $this->from['name']

2023-04-21 09:33 UTC, hatik92 commented on src/Libraries/Mailer/Adapters/SmtpAdapter.php
> +        $this->mailer->Password = $params['password'];
params keys add mail_

2023-04-21 09:51 UTC, hatik92 commented on src/Libraries/Mailer/Adapters/SmtpAdapter.php
> +            $this->mailer->Body = $body;
replase
$this->mailer->Body = trim(str_replace("\n", "", $body));

2023-04-21 11:16 UTC, hatik92 commented on tests/unit/_root/shared/config/mailer.php
> +        'password' => 'test'
keys add mail_

2023-04-21 14:01 UTC, hatik92 approved these changes

2023-04-21 14:59 UTC, hatik92 approved these changes

2023-04-23 09:17 UTC, andrey-smaelov approved these changes

2023-04-23 09:19 UTC, merged