Pagination feature
softberg/quantum-php-core pull request #154
Opened 2024-09-09 15:00 UTC by Vahram1995

2024-09-09 17:06 UTC, andrey-smaelov commented on src/Libraries/Database/Sleekdb/Paginator.php
> +			$previous = $this->getUri($withBaseUrl) . 'per_page=' . $this->per_page . '&page=' . $this->previousPageNumber();
`per_page` and `page` are spread over the code where can be used as constants

2024-09-09 17:07 UTC, andrey-smaelov commented on src/Libraries/Database/Sleekdb/Paginator.php
> +	protected $per_page;
Variables and properties are always should be in camel case

2024-09-09 17:24 UTC, armanist requested changes

2024-09-09 17:24 UTC, armanist commented on src/Libraries/Database/Idiorm/Paginator.php
> +		return $this->data[array_key_first($this->data)];
It seems like` $this->data` can also be of type `IdiormResultSe`t; however, parameter `$array` of `array_key_first()` does only seem to accept array, maybe add an additional type check?

2024-09-09 17:24 UTC, armanist commented on src/Libraries/Database/Idiorm/Paginator.php
> +		return $this->data[array_key_last($this->data)];
It seems like `$this->data` can also be of type `IdiormResultSet`; however, parameter `$array` of `array_key_last()` does only seem to accept array, maybe add an additional type check?

2024-09-09 17:24 UTC, armanist commented on src/Libraries/Database/Sleekdb/Paginator.php
> +	public function getPagination(bool $withBaseUrl = false, $pageItemsCount = null): ?string
`getPagination()` method is defined in 2 places [code duplicate]

2024-09-09 17:24 UTC, armanist commented on src/Libraries/Database/Sleekdb/Paginator.php
> +	public function getPagination(bool $withBaseUrl = false, $pageItemsCount = null): ?string
`getPagination()`  too much conditions, complexity is very high

2024-09-10 17:01 UTC, armanist approved these changes

2024-09-11 12:39 UTC, Arno2005 approved these changes

2024-09-11 12:39 UTC, merged