149 View cache
softberg/quantum-php-core pull request #178
Opened 2024-11-14 11:15 UTC by Vahram1995

2024-11-14 17:32 UTC, armanist requested changes
First please look at scrutinizer issues and fix them.

The library uses code PHP functionality, but instead it should use every available functions from framework.

The approach of storing `ttl` into the content is not desirable

serializing the content can lead potential problems

2024-11-14 17:32 UTC, armanist commented on src/Libraries/ResourceCache/ViewCache.php
> +		file_put_contents($cacheFile, serialize($data));
Are we using temp files or regular files?

2024-11-14 17:32 UTC, armanist commented on src/Libraries/ResourceCache/ViewCache.php
> +		file_put_contents($cacheFile, serialize($data));
Why we store the `ttl` inside the content?

2024-11-14 17:32 UTC, armanist commented on tests/unit/_root/shared/config/config.php
> +	'resource_cache' => true,
Let's use `cache => true`

2024-11-15 15:10 UTC, Arno2005 commented on src/Router/Route.php
> +	public function cacheable(bool $shouldCache, int $ttl = null): Route
Missing doc block in some methods.

2024-11-15 15:17 UTC, Arno2005 commented on tests/unit/Libraries/ResourceCache/ViewCacheTest.php
> +
The two tests above are the same, if there are no code-wise differences in these tests, maybe remove one of them?

2024-11-15 15:19 UTC, Arno2005 requested changes
Add the missing doc blocks and remove duplicate unit tests.

2024-11-15 16:40 UTC, armanist requested changes
There are still several unresolved point, but also check the scrutinizer first

2024-11-15 16:40 UTC, armanist commented on src/Mvc/QtView.php
> +        return $content;
If route is cacheable and also minifiable, this return still returns normal rendered view

2024-11-15 16:40 UTC, armanist commented on src/Router/Route.php
> +use Quantum\Loader\Setup;
Keep use statements in order

2024-11-15 16:40 UTC, armanist commented on src/Router/Route.php
> +		if (!empty(session()->getId())){
if `session()->getId()` is empty the the whole function just returns `$this`, so the above code is unnecessary

```
if (!$ttl) {
			$ttl = config()->get('view_cache.ttl', 300);
		}
```

2024-11-15 16:40 UTC, armanist commented on src/Router/Route.php
> +		if (!empty(session()->getId())){
Use early return instead of nesting

2024-11-15 16:40 UTC, armanist commented on src/Router/Route.php
> +			!empty(session()->getId()) &&
Checking `session()->getId()` might be unnecessary

2024-11-27 11:42 UTC, armanist requested changes

2024-11-27 11:42 UTC, armanist commented on src/Libraries/ResourceCache/ViewCache.php
> +		if (!self::$fs->isDirectory($this->cacheDir) && !$fromCommand) {
Please check the need of `$fromCommand`

2024-11-27 11:42 UTC, armanist commented on src/Libraries/ResourceCache/ViewCache.php
> +		$cacheFile = (new self())->getCacheFile($key, $sessionId);
Why the method called via `new self()` vs `$this`

2024-11-27 11:42 UTC, armanist commented on src/Libraries/ResourceCache/ViewCache.php
> +			throw ConfigException::configCollision('view_cache');
`configCollision()` is not correct throw in this case

2024-11-27 11:42 UTC, armanist commented on src/Mvc/MvcManager.php
> +			ViewCache::exists(route_uri(), session()->getId(), $cacheSettings['ttl'])
`ViewCache::exists` creates instance inside the method, and the next instance is created few lines bellow.
It leads to apply singleton approach

2024-11-27 11:42 UTC, armanist commented on src/Mvc/MvcManager.php
> +				$content = (new ViewCache())->get(route_uri(), session()->getId(), $cacheSettings['ttl']);
Once the `ViewCache` implements singleton the access to the class can be unified

2024-11-27 11:42 UTC, armanist commented on src/Mvc/QtView.php
> +		    $content = (new ViewCache())
`ViewCache` will be access via singleton

2024-11-27 11:42 UTC, armanist commented on src/Libraries/ResourceCache/ViewCache.php
> +class ViewCache
Implement singleton pattern

2024-11-27 14:00 UTC, armanist requested changes

2024-11-27 14:00 UTC, armanist commented on src/Libraries/ResourceCache/ViewCache.php
> +	private static function getCacheDir(): string
Use non static functions

2024-11-27 14:00 UTC, armanist commented on src/Libraries/ResourceCache/ViewCache.php
> +	public function exists(string $key, string $sessionId, int $ttl): bool
Method `exists()` doesn't follow single responsibility principle, it does check as well as remove

2024-11-28 17:22 UTC, armanist requested changes

2024-11-28 17:22 UTC, armanist commented on src/Libraries/ResourceCache/ViewCache.php
> +		if (!$this->fs->exists($cacheFile)) {
It should use `$this->exists()`

2024-11-30 16:12 UTC, armanist requested changes
The latest changes introduced some inconsistencies.. 

The `ttl` property of `ViewCache` is set from `Route`  class while `isEnabled` is set from `Router` class.

We need to keep consistency on similar operations applied on same object.

It's obvious now that these both things (`ttl` and `isEnabled`) should be set from `Router` class after the current route is known. Therefore there would no need of passing `ViewCache` instance to `Route` class anymore.

2024-11-30 16:12 UTC, armanist commented on tests/unit/Router/RouteTest.php
> +	    Mockery::mock('Quantum\Libraries\ResourceCache\ViewCache');
Why we are mocking `ViewCache` here?

2024-11-30 16:12 UTC, armanist commented on src/Router/Router.php
> +	    if (is_array($currentRoute) && key_exists('shouldCache', $currentRoute)){
This section should be placed after this condition, and there wouldn't need to check it's array or not

```
if (!$currentRoute) {
    throw RouteException::incorrectMethod($this->request->getMethod());
}
```

2024-12-02 11:56 UTC, armanist approved these changes

2024-12-02 12:02 UTC, andrey-smaelov approved these changes

2024-12-02 12:13 UTC, Arno2005 approved these changes

2024-12-02 12:15 UTC, merged