Migration feature
softberg/quantum-php-core pull request #65
Opened 2022-05-17 08:53 UTC by armanist

2022-05-18 11:15 UTC, andrey-smaelov requested changes
Please check comments and apply changes

2022-05-18 11:15 UTC, andrey-smaelov commented on src/Migration/MigrationTemplate.php
> +use Quantum\Libraries\Database\Type;
The Type class import path is not correct

2022-05-18 12:52 UTC, andrey-smaelov approved these changes

2022-05-18 16:04 UTC, Vahram1995 commented on src/Libraries/Database/Schema/Column.php
> +        return isset($this->$property) && ($action != self::RENAME && $action != self::DROP) ? $this->$property : null;
have all the conditions in a single parentheses

2022-05-19 07:44 UTC, grigoryanmartin20 approved these changes

2022-05-19 09:39 UTC, Vahram1995 approved these changes

2022-05-19 11:47 UTC, Vahram1995 approved these changes

2022-05-19 11:48 UTC, merged