Hooks logic update and more
softberg/quantum-php-core pull request #68
Opened 2022-06-06 16:56 UTC by armanist

2022-06-06 17:07 UTC, andrey-smaelov approved these changes

2022-06-07 08:54 UTC, Vahram1995 commented on src/Helpers/url.php
> + * @param integer $code
integer should be int

2022-06-07 09:59 UTC, Vahram1995 commented on src/Http/Response/HttpResponse.php
>       * @param int|null $code
remove null

2022-06-07 10:01 UTC, Vahram1995 commented on src/Http/Response/HttpResponse.php
>       * @param string|null $callback
remove null

2022-06-07 10:12 UTC, Vahram1995 commented on tests/unit/Helpers/HelperTest.php
> +        ;
remove semicolon

2022-06-07 10:18 UTC, Vahram1995 commented on tests/unit/Http/ResponseTest.php
> +                    ],);
remove comma

2022-06-07 10:27 UTC, Vahram1995 requested changes
please check comments

2022-06-07 10:49 UTC, Vahram1995 approved these changes

2022-06-07 10:50 UTC, merged