Swager integration for API module
softberg/quantum-php-core pull request #87
Opened 2022-09-30 15:22 UTC by hatik92

2022-09-30 17:13 UTC, armanist requested changes
Use FileSystem class whenever possible

2022-10-03 12:13 UTC, armanist requested changes

2022-10-03 12:13 UTC, armanist commented on src/Console/Commands/OpenApiUiAssetsCommand.php
> +    protected $name = 'install:openApi';
all lower case

2022-10-03 12:13 UTC, armanist commented on src/Console/Commands/OpenApiUiAssetsCommand.php
> +    protected $description = 'Generates files for openApi ui';
description text should be: Generates files for OpenApi UI

2022-10-03 12:13 UTC, armanist commented on src/Console/Commands/OpenApiUiAssetsCommand.php
> +    protected $help = 'The command will publish openApi ui resources';
The command will publish OpenApi UI resources

2022-10-03 12:13 UTC, armanist commented on src/Console/Commands/OpenApiUiAssetsCommand.php
> +        if (!is_dir($modulePath)) {
Use FileSystem library

2022-10-03 12:13 UTC, armanist commented on src/Console/Commands/OpenApiUiAssetsCommand.php
> +            $fp = fopen($modulePath . DS . 'Resources' . DS . "opanApi" . DS . "docs.json", "wb");
For which reason the fopen() function is used? what is the "wb"?

2022-10-03 12:13 UTC, armanist commented on src/Console/Commands/OpenApiUiAssetsCommand.php
> +        if (installed(assets_dir() . DS . 'OpenApiUi' . DS . 'index.css')) {
This will throw error for next modules if attempted, rather it should check installed() with module pair

2022-10-03 15:25 UTC, Vahram1995 commented on src/Console/Commands/OpenApiUiAssetsCommand.php
> +        exec(base_dir() . DS . 'vendor/bin/openapi modules/' . $module . '/Controllers/ -o modules/' . $module . '/Resources/opanApi/docs.json');
replace '/' to DS

2022-10-03 15:26 UTC, Vahram1995 commented on src/Console/Commands/OpenApiUiAssetsCommand.php
> +                    copy($this->vendorOpenApiFolderPath . '/' . $file, $this->publicOpenApiFolderPath . '/' . $file);
replace '/' to DS

2022-10-03 15:27 UTC, Vahram1995 commented on src/Console/Commands/DebugBarAssetsCommand.php
> +                    if ($this->fs->isDirectory($src . '/' . $file)) {
replace '/' to DS

2022-10-03 15:42 UTC, armanist requested changes

2022-10-03 15:42 UTC, armanist commented on src/Console/Commands/OpenApiUiAssetsCommand.php
> +            $fp = fopen($modulePath . DS . 'Resources' . DS . "openApi" . DS . "docs.json", "w");
Use $fs->put() with empty content

2022-10-03 15:42 UTC, armanist commented on src/Console/Commands/OpenApiUiAssetsCommand.php
> +        if ($this->fs->exists($modulePath . DS . 'openApi' . DS . 'docs.json')) {
How we prevent installation for same module, if it's already insatlled?

2022-10-03 15:42 UTC, armanist commented on src/Console/Commands/DebugBarAssetsCommand.php
> +    protected $fs;
Add doc-block for the paramter

2022-10-04 14:16 UTC, armanist approved these changes

2022-10-04 14:44 UTC, armanist approved these changes

2022-10-05 15:06 UTC, armanist requested changes

2022-10-05 15:06 UTC, armanist commented on src/Console/Commands/OpenApiUiAssetsCommand.php
> +    //$route->group("openapi", function ($route) {
This group section now can be uncommented

2022-10-05 15:06 UTC, armanist commented on src/Console/Commands/OpenApiUiAssetsCommand.php
> +        if (strpos($this->fs->get($file), '$route->group("openapi", function ($route) {') === false) {
Instead of this we can load all routes and then use route_group_exists() helper method to check if the group exists or not

2022-10-05 15:11 UTC, Vahram1995 commented on src/Console/Commands/DebugBarAssetsCommand.php
> +
remove empty line

2022-10-05 15:15 UTC, Vahram1995 commented on src/Console/Commands/OpenApiUiAssetsCommand.php
> +        $route->get("' . strtolower($module) . '/documentation", function (Quantum\Http\Response $response) {
change '/' to DS

2022-10-05 15:26 UTC, Vahram1995 requested changes

2022-10-13 09:24 UTC, andrey-smaelov approved these changes

2022-10-13 09:24 UTC, armanist approved these changes

2022-10-13 09:25 UTC, merged